# Generated by Django 4.2.7 on 2026-01-14 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfile',
            old_name='name',
            new_name='original_name',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='size',
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='file_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='file_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
