# Generated by Django 4.2.7 on 2026-01-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_name_projectfile_original_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Ordering of task within sprint/status column', null=True),
        ),
    ]
