# Generated by Django 4.2.7 on 2025-08-07 11:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_projectusermapping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectUserMapping',
            new_name='UserMapping',
        ),
        migrations.AlterModelOptions(
            name='usermapping',
            options={'verbose_name': 'UserMapping', 'verbose_name_plural': 'UserMappings'},
        ),
    ]
