# Generated by Django 4.2.7 on 2025-08-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0006_leavebalance'),
        ('projects', '0006_rename_projectusermapping_usermapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermapping',
            name='user',
        ),
        migrations.AddField(
            model_name='usermapping',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='hr_management.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='hr_management.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='hr_management.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brought_projects', to='hr_management.employee'),
        ),
        migrations.AlterField(
            model_name='usermapping',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='hr_management.employee'),
        ),
    ]
