# Generated by Django 4.2.7 on 2025-08-08 08:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0006_leavebalance'),
        ('projects', '0008_remove_project_company_remove_project_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermapping',
            name='manager',
        ),
        migrations.CreateModel(
            name='ManagerMapping',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='hr_management.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'ManagerMapping',
                'verbose_name_plural': 'ManagerMappings',
            },
        ),
    ]
