# Generated by Django 4.2.7 on 2025-08-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_sprint_projects_milestone_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
