# Generated by Django 4.2.7 on 2025-08-19 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0006_leavebalance'),
        ('projects', '0013_epic_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='project_files/%Y/%m/%d/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('extension', models.CharField(blank=True, max_length=16)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_management.employee')),
            ],
            options={
                'verbose_name': 'ProjectFile',
                'verbose_name_plural': 'ProjectFiles',
            },
        ),
    ]
