# Generated by Django 4.2.7 on 2026-01-04 12:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_taskstatushistory_projectmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Workflow', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('is_terminal', models.BooleanField(default=False)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='projects.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowed_roles', models.JSONField(default=list)),
                ('require_assignee', models.BooleanField(default=False)),
                ('require_comment', models.BooleanField(default=False)),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transitions', to='projects.workflowstatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transitions', to='projects.workflowstatus')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='projects.workflow')),
            ],
        ),
    ]
