# Generated by Django 4.2.7 on 2026-01-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_workflow_workflowstatus_workflowtransition'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatushistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
