# Generated by Django 4.2.7 on 2026-01-08 18:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_taskstatushistory_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintAISnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('probability', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_snapshots', to='projects.sprint')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
