# Generated by Django 4.2.7 on 2025-07-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('company', '0001_initial'),
        ('hr_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
