# Generated by Django 4.2.7 on 2025-07-09 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_management', '0002_employee_comp_id_alter_employee_dept_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='comp_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dept_id',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
