# Generated by Django 4.2.7 on 2025-08-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0005_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=24)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee')),
            ],
        ),
    ]
