# Generated by Django 4.2.7 on 2025-12-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0007_leaverequest_approved_at_leaverequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_payroll_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_regime',
            field=models.CharField(choices=[('OLD', 'Old'), ('NEW', 'New')], default='NEW', max_length=10),
        ),
    ]
