# Generated by Django 4.2.7 on 2026-01-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0009_employee_bank_account_number_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='comments',
            field=models.TextField(blank=True, help_text="Approver's comments", null=True),
        ),
    ]
