# Generated by Django 4.2.7 on 2026-01-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0010_alter_leaverequest_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pan',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
