# Generated by Django 4.2.7 on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0011_employee_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(
                choices=[
                    ('CASUAL', 'Casual'),
                    ('SICK', 'Sick'),
                    ('EARNED', 'Earned'),
                    ('MATERNITY', 'Maternity'),
                    ('PATERNITY', 'Paternity'),
                    ('OTHER', 'Other'),
                ],
                default='CASUAL',
                max_length=20,
            ),
        ),
    ]
