# Generated by Django 4.2.7 on 2025-07-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='user_id',
            new_name='user',
        ),
    ]
