# Generated by Django 4.2.7 on 2025-09-02 08:19

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_tracking', '0002_rename_user_id_timeentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timeentry',
            unique_together={('user', 'date')},
        ),
    ]
