# Generated by Django 4.2.7 on 2025-07-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('HR', 'Hr'), ('MANAGER', 'Manager')], db_index=True, max_length=10, null=True),
        ),
    ]
