# Generated by Django 4.2.7 on 2025-08-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_date_of_joining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
