# Generated by Django 4.2.7 on 2025-12-20 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('FINALIZED', 'Finalized'), ('POSTED', 'Posted')], default='DRAFT', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('total_gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payruns_created', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payruns_finalized', to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pay_run', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'payrun',
            },
        ),
        migrations.DeleteModel(
            name='PerformanceMetric',
        ),
        migrations.AddField(
            model_name='payroll',
            name='pay_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.payrun'),
        ),
    ]
