# Generated by Django 4.2.7 on 2025-12-22 18:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0008_employee_is_payroll_active_employee_tax_regime'),
        ('payroll', '0002_payrun_delete_performancemetric_payroll_pay_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='attendance_bonus',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='health_insurance',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='medical_allowance',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='overtime_amount',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='overtime_hours',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='overtime_rate',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='performance_bonus',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='project_bonus',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='house_rent_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='income_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pay_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payrun'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollperiod'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='provident_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('CALCULATED', 'Calculated'), ('APPROVED', 'Approved')], default='CALCULATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
