# Generated by Django 4.2.7 on 2025-12-22 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_payroll_attendance_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=10)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENTAGE', 'Percentage')], max_length=15)),
                ('percentage_of', models.CharField(blank=True, choices=[('BASIC', 'Basic'), ('GROSS', 'Gross')], max_length=10, null=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'salary_component',
                'verbose_name_plural': 'salary_components',
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='performance_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='project_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll')),
            ],
            options={
                'verbose_name': 'payroll_component',
                'verbose_name_plural': 'payroll_components',
            },
        ),
    ]
