# Generated by Django 4.2.7 on 2025-12-27 13:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_companyusermapping_usermapping_and_more'),
        ('payroll', '0005_alter_benefitenrollment_id_alter_benefitplan_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryChallan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statutory_type', models.CharField(choices=[('PF', 'Provident Fund'), ('PT', 'Professional Tax'), ('TDS', 'Tax Deducted at Source')], max_length=10)),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('challan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='challans/')),
                ('status', models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='DUE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'unique_together': {('company', 'statutory_type', 'month', 'year')},
            },
        ),
    ]
