# Generated by Django 4.2.7 on 2025-12-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_statutorychallan'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutorychallan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
