# Generated by Django 4.2.7 on 2025-12-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_statutorychallan_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='lop_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='working_days',
            field=models.IntegerField(default=0),
        ),
    ]
