# Generated by Django 4.2.7 on 2025-12-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payroll_lop_days_payroll_paid_leave_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payable_days',
            field=models.IntegerField(default=0),
        ),
    ]
