# Generated by Django 4.2.7 on 2025-12-29 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0010_payrollauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRollbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('rolled_back_at', models.DateTimeField(auto_now_add=True)),
                ('pay_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_logs', to='payroll.payrun')),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
