# Generated by Django 4.2.7 on 2025-12-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_payrollrollbacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='financial_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
