# Generated by Django 4.2.7 on 2026-01-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_payrollperiod_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrun',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrun',
            name='locked_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payrun',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
