# Generated by Django 4.2.7 on 2026-01-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_pan_company_tan'),
        ('payroll', '0013_payrun_is_locked_payrun_locked_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarycomponent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='company.company'),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='is_statutory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='calculation_type',
            field=models.CharField(blank=True, choices=[('FIXED', 'Fixed'), ('PERCENTAGE', 'Percentage')], max_length=15),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='component_type',
            field=models.CharField(blank=True, choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='is_taxable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
