# Generated by Django 4.2.7 on 2026-01-26 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0014_remove_salarycomponent_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponentAuditLog',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('TOGGLED', 'Toggled')], max_length=20)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payroll.salarycomponent')),
            ],
            options={
                'verbose_name': 'SalaryComponentAuditLog',
                'verbose_name_plural': 'SalaryComponentAuditLogs',
            },
        ),
    ]
