# Generated by Django 4.2.7 on 2026-01-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_companyusermapping_usermapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pan',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tan',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
